name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  backend:
    name: Backend (Django) - lint & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r planningBack/requirements.txt

      - name: Django system check
        run: |
          cd planningBack
          python manage.py check

  frontend:
    name: Frontend (Angular) - lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: planningFront
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Pas de package-lock.json → on utilise npm install
      - name: Install deps
        run: npm install
      - name: Lint (non bloquant si tu n'as pas encore configuré)
        run: npm run lint || echo "lint warnings"
      - name: Build
        run: npm run build --if-present