name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  backend:
    name: Backend (Django) - checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: planningBack
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      # Si tu n'as pas de tests pour l’instant, on fait au moins un check Django
      - name: Django system check
        env:
          DJANGO_SETTINGS_MODULE: planningBack.settings
        run: python manage.py check
      # Quand tu auras des tests :
      # - name: Run tests
      #   run: python manage.py test

  frontend:
    name: Frontend (Angular) - lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: planningFront
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: planningFront/package-lock.json
      # Pas de package-lock.json → on utilise npm install pour l’instant
      - name: Install deps
        run: npm install
      - name: Lint (non bloquant si tu n'as pas encore configuré)
        run: npm run lint || echo "lint warnings"
      - name: Build
        run: npm run build --if-present