name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  backend:
    name: Backend (Django) - lint & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Afficher l’arborescence
        run: |
          pwd
          ls -la
          ls -la planningBack || true
          ls -la planningFront || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Créer .env pour la CI
        run: |
          cat > planningBack/.env << 'EOF'
          SECRET_KEY=ci-secret-key
          DEBUG=True
          DATABASE_URL=sqlite:///db.sqlite3
          ALLOWED_HOSTS=*
          CSRF_TRUSTED_ORIGINS=https://planeasy.localhost
          EOF

      - name: Installer les dépendances backend
        run: pip install -r planningBack/requirements.txt

      - name: Installer libs de test
        run: pip install pytest pytest-django pytest-cov

      - name: Vérifier Django
        run: |
          cd planningBack
          python manage.py check

      - name: Lancer les tests (JUnit + coverage)
        working-directory: planningBack
        env:
          DJANGO_SETTINGS_MODULE: planningBack.settings
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=. --cov-report=xml:coverage.xml \
            --junitxml=pytest-junit.xml

      - name: Publier les rapports de test
        uses: actions/upload-artifact@v4
        with:
          name: backend-rapports
          path: |
            planningBack/pytest-junit.xml
            planningBack/coverage.xml

  frontend:
    name: Frontend (Angular) - lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: planningFront
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Afficher l’arborescence
        run: |
          pwd
          ls -la
          ls -la planningFront || true

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: planningFront/package-lock.json

      # Pas de package-lock.json → npm install au lieu de npm ci
      - name: Installer les dépendances frontend
        run: npm install

      - name: Lint (non bloquant)
        run: npm run lint || echo "lint warnings"

      - name: Build
        run: npm run build --if-present